### ISSUE TITLE
Install scReadCounts

### ISSUE THREAD

**Issue by lucia-ramirez** [HorvathLab/NGS#2]
Hello, I installed the SCReadCounts-1.1.6.Linux-x86_64 version (I am using python3.7) and I am trying to run the example but I keep getting this error:

../bin/scReadCounts -r singlecell_chr17.bam -s singlecell_222_5_chr17.txt -m 3 -o singlecell-output.tsv
[385] Failed to execute script readCounts
Traceback (most recent call last):
  File "readCounts.py", line 380, in <module>
  File "pileups.py", line 44, in iterator
  File "util.py", line 523, in group
  File "util.py", line 700, in group
AttributeError: 'ReadNameWord' object has no attribute 'whilelisted'
[65210] Failed to execute script scReadCounts
Traceback (most recent call last):
  File "scReadCounts.py", line 262, in <module>
  File "execute.py", line 30, in execute
AssertionError

I also tried to install it on another computer (MacOs) and had the same problem

Thanks,

Lucia

**Comment by edwardsnj** [comment]
I just pushed a new release (1.1.7) you should find this fixes the issue.
