### ISSUE TITLE
readCounts -G

### ISSUE THREAD

**Issue by lucia-ramirez** [HorvathLab/NGS#3]
Hi

I am trying to run scReadCounts with -G STARsolo but I keep getting the following error:

[20591] Failed to execute script readCounts
Traceback (most recent call last):
  File "readCounts.py", line 401, in <module>
TypeError: '<' not supported between instances of 'NoneType' and 'str'
[20529] Failed to execute script scReadCounts
Traceback (most recent call last):
  File "scReadCounts.py", line 262, in <module>
  File "execute.py", line 30, in execute
AssertionError

I am using the latest version (1.1.7)

Thanks

**Comment by edwardsnj** [comment]
[SCReadCounts-1.1.8 ](https://github.com/HorvathLab/NGS/releases/tag/SCReadCounts-1.1.8) released.
